settings_dir="$HOME/.dotfiles/zsh"

autoload -U compinit
compinit

setopt extendedglob
setopt NO_NOMATCH

source $settings_dir/history.zsh
source $settings_dir/completion.zsh
source $settings_dir/prompt.zsh
source $settings_dir/aliases.zsh

# Path setting
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

### Per-machine settings
for file in ~/.{environment,extra}; do
  if [ -f "$file" ]; then
  	source "$file"
  fi
done
unset file

