### Path setting
export PATH=$PATH:/usr/local/bin:/usr/local/sbin

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="gentoo"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  git
  git-extras
  virtualenv
  aws
  docker
  common-aliases
  # gpg-agent
  httpie
  npm
  pip
  vagrant
  colored-man-pages
  colorize
  extract
  golang
  # autoenv
  wd)

source $ZSH/oh-my-zsh.sh
source ~/.dotfiles/bash/common.sh
