# file: bash_profile

# Source ~/.bashrc if exists
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/foxmk/Downloads/google-cloud-sdk/path.bash.inc ]; then
  source '/Users/foxmk/Downloads/google-cloud-sdk/path.bash.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/foxmk/Downloads/google-cloud-sdk/completion.bash.inc ]; then
  source '/Users/foxmk/Downloads/google-cloud-sdk/completion.bash.inc'
fi

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
